### ISSUE TITLE
BUG:  Aggregator script has failures while manipulating a vector of strings

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/japan#104]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): HEAD and 5342c95 (first revision with the aggregator)
- OS or system: Linux (apar@adaq2 & adaq3)
- Special ROOT or Geant4 versions? 6.12-06

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Set up the normal japan environment
2. "cd japan/rootScripts/aggregator"
3. "source setup_camguin.tcsh"
4. "./panguin_wrapper.sh -f anaInt.cfg -r 1460 -n 1"

### Expected Result: (what do you expect when you execute the steps above)
There would be plots produced in the panguin window.

### Actual Result: (what do you get when you execute the steps above)
Repeated messages like:
> IncrementalExecutor::executeFunction: symbol '_ZSt7forwardIRKSt6vectorISsSaISsEEEOT_RNSt16remove_referenceIS5_E4typeE' unresolved while linking [cling interface function]!
> You are probably missing the definition of std::vector<std::string, std::allocator<std::string> > const& std::forward<std::vector<std::string, std::allocator<std::string> > const&>(std::remove_reference<std::vector<std::string, std::allocator<std::string> > const&>::type&)
> Maybe you need to load the corresponding shared library?

No plots are produced in the panguin window.

**Comment by paulmking** [comment]
I'm not quite sure why the aggregator is being run using panguin, as the actual mechanic is by calling a macro to independently open the file and the tree over and over again, and doesn't really communicate with panguin for much.

It might be just as good to have it be built with its own wrapper to make the function calls, or perhaps better to just open the file once and then pass the tree into the data extractor function calls.

**Comment by cameronc137** [comment]
Correct. I built it to work with all of these options. The Panguin business was just as an example of how to include this framework for storing some output analyzed numbers simultaneously with the online analysis procedure the shift crew will do... changes and automation optimization are welcome and easily implemented.

**Comment by paulmking** [comment]
@cameronc137 Under what environment are you able to run the panguin version of the aggregator?  It seems to always give these errors when using a ROOT6 compiled panguin, and if I hack a version of panguin to compile with the root 5.34 on apar@adaq3, I get a whole bunch of other errors.

What are your steps to get a working version?

**Comment by paulmking** [comment]
@cameronc137 
The problem comes in with commit 5342c95, where you introduced the postpan processing.

In revision 9a588e8 (the one just before 5342c95), the command, `./panguin_wrapper.sh -f anaInt.cfg -r 1460 -n 1`, proceeds without errors.

`git diff 9a588e8 5342c95` shows that all the changes are in the aggregator source files.

**Comment by rahmans1** [comment]
It might be better to just adapt the postpan wrapper to call camguin directly instead of through panguin. Right now i can get camguin to compile without any errors by itself and run it. However, there is a memory leak warning during runtime. 
[apar@aonl1 ~/rahmans/japan/rootScripts/aggregator]$ root -q -b camguin.C'( "meanrms","evt","bcm_an_ds3","hw_sum","defaultCuts",0,"clean", 1357,1 )'

Processing camguin.C( "meanrms","evt","bcm_an_ds3","hw_sum","defaultCuts",0,"clean", 1357,1 )...
Analysis: meanrms
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
Warning in <TROOT::Append>: Replacing existing TH1: htemp_rebin (Potential memory leak).
Warning in <TROOT::Append>: Replacing existing TH1: htemp_rebin (Potential memory leak).
Warning in <TROOT::Append>: Replacing existing TH1: htemp_rebin (Potential memory leak).

**Comment by cameronc137** [comment]
The issue comes not from utilizing panguin, but from trying to execute the series of macros twice without fully cleaning up all memory first I think. I can get any version of the macros to run fine on a first pass, but even in interactive root if I execute a second macro in the same ROOT session it will give the same kinds of errors. I suspect I need to free up some memory somewhere, but I'm not sure where as the error appears to be immediate upon reexecution.

Also it may have to do with the compiler, see an example of another person having similar issues: https://sft.its.cern.ch/jira/browse/ROOT-7978

**Comment by paulmking** [comment]
Resolved in develop by pull request #105

**Comment by cameronc137** [comment]
The bug if caused by exactly this single line by itself when the macro is executed a second time within one single root session: https://github.com/JeffersonLab/japan/blob/87b19a703ce1f9372fa9e5ae8fabb37f228a8442/rootScripts/aggregator/camIO.hh#L109

**Comment by cameronc137** [comment]
The exact error message returned is

IncrementalExecutor::executeFunction: symbol '_ZSt7forwardIRKSt6vectorISsSaISsEEEOT_RNSt16remove_referenceIS5_E4typeE' unresolved while linking [cling interface function]!
You are probably missing the definition of std::vector<std::string, std::allocator<std::string> > const& std::forward<std::vector<std::string, std::allocator<std::string> > const&>(std::remove_reference<std::vector<std::string, std::allocator<std::string> > const&>::type&)
Maybe you need to load the corresponding shared library?

**Comment by cameronc137** [comment]
Fixed in #109
