### ISSUE TITLE
Add the "bpmelli" variable to the Stripline BPM class

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/japan#14]
Caryn's "bpmelli" variables should be added to the Stripline BPM class.  These should be calculated during the ProcessEvent function, and a helicity-correlated difference should be calculated, just as is done for the positions. 

This will also require a new calibration parameter representing the nominal beam spot size at that BPM.

**Comment by paulmking** [comment]
![bpbelli_formula_from_caryn](https://user-images.githubusercontent.com/8117420/52894230-411e8f80-3174-11e9-8393-4e20797a3af0.png)

The above are notes from Caryn about how to calculate the BPM ellipticity.

**Comment by cameronc137** [comment]
This ellipticity is correctly obtained in the code now. I just copied every single instance of the effective charge object and calculated it simply as the x's - y's / sum of both (i.e. no fancy scale factors yet, since I don't know them and they will probably need to be in the beamline geometry maps anyway, and they aren't that important since this normalization will vanish in the asymmetry...).

**Comment by cameronc137** [comment]
[calcElli.pdf](https://github.com/JeffersonLab/japan/files/3139817/calcElli.pdf)
[corrElli.pdf](https://github.com/JeffersonLab/japan/files/3139818/corrElli.pdf)
[diffElli.pdf](https://github.com/JeffersonLab/japan/files/3139819/diffElli.pdf)
[japanElli.pdf](https://github.com/JeffersonLab/japan/files/3139820/japanElli.pdf)

**Comment by cameronc137** [comment]
I'm adding the correction subtraction now and scaling the original ellipticity by 0.5*fQwStriplineCalibration^2 (which is 18.81mm)

**Comment by cameronc137** [comment]
Commit c3cfa7b36461b71055e93deaa5b0988d4c5207ec adds in the 18.81^2 scale factor and the 1st order correction -0.250014*(x^2-y^2).

There is one concern: I had to drop the BSENfactor scaling on the 18.81 and 0.250014 because I don't think it should be applied here.... What is BSENfactor, why isn't it defined in the code, and should it be applied to the 18.81 numbers?

**Comment by paulmking** [comment]
This is resolved in develop by pull request #111
