### ISSUE TITLE
Enhancement: print out help when running without arguments

### ISSUE THREAD

**Issue by cipriangal** [JeffersonLab/japan#43]
I'd suggest we print out instructions when running one of the executables without any arguments.

For the default behaviour (whatever we think that should be), I'd suggest we just have an argument ("--default") that does that.

**Comment by cipriangal** [comment]
When running with arguments it would be useful to have them print out what the code expects it will happen. For example if it assumes a path for the rootfile it will print out something like:
"looking for file: ../path/to/your/file.root"

**Comment by wdconinc** [comment]
Don't we have that in effect?
- The output is not the same as --help (which is more complete). I seem to remember that there was a technical reason for this. A first step would be to move `DefineOptionsParity(gQwOptions);` before the `if(argc == 1)` catch.
- This does not seem to work for qwmockdatagenerator. Probably just needs a similar catch.

```
15:02:26 wdconinc@herakles ~/git/japan $ bin/qwparity

Welcome to the Qweak analyzer code.

Default options:
  --usage                 print this help message
  -h [ --help ]           print this help message
  -V [ --version ]        print the version string
  -c [ --config ] arg     read ONLY this config file
                          (will override default config files)
  -a [ --add-config ] arg read ALSO this config file
                          (will keep the default config files)

```

**Comment by cipriangal** [comment]
yeah

**Comment by wdconinc** [comment]
I don't have access to adaq right now, so I can't debug as easily. It may be caused by different ROOT versions used when linking and when running.

**Comment by paulmking** [comment]
This is definitely due to having different ROOT versions used for the compilation and execution.

The apar@adaq environment seems to have been changed to have ROOT/5.34.36 set up on login, and you were using ROOT/6.12-06 when you built the analyzer.

I had been unable to successfully build the code on apar@adaq3 using the default login environment and had to clear and rest the *path variables and add a new rootsys to get it to work.

We should discuss how we want the apar environment to be set up.

**Comment by paulmking** [comment]
On apar@adaq, doing "source ~/pking/reset_env.csh" will give you a working ROOT/6.12-06 enviroment

**Comment by cipriangal** [comment]
Good catch. I'll work on this today and probably close the issue if things work as Wouter pointed out above.

**Comment by wdconinc** [comment]
@paulmking If we can avoid having to run a setup script before running the analyzer, I'd definitely think that's better. I have different ROOT versions installed on my local servers and there is no confusion there. I think we need to figure out how to use rpath or so to fix the location on compilation instead of assuming that any good ol' libroot.so in the LD search path will do.

**Comment by wdconinc** [comment]
I've added more output when no commands in 99c6fd959a487a3e28b1510c9f2c1d18b41566cb. I think that resolves this. Please close if you agree.

**Comment by cipriangal** [comment]
@wdconinc: Thanks. I kept this open so that I remember that you said you should be able to find the correct root using rpath. Since you opened up a branch for this I think it's fine to just close this off.
