### ISSUE TITLE
Root file refreshing is broken in panguin

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/japan#84]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): HEAD
- OS or system: apar@adaq3
- Standard install of develop

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Comment out this line (https://github.com/JeffersonLab/japan/blob/4d495cb831d3cb10e58a822522d08390e7412602/panguin/src/panguinOnline.cc#L669) and run panguin in watchfile mode on an online-japan produced ROOT file

### Expected Result: (what do you expect when you execute the steps above)
Without commenting out the refresh line I would expect to get good online plots all the time

### Actual Result: (what do you get when you execute the steps above)
The default behavior erases the initially drawn information. When I comment out refresh it will at least re-draw correctly, but stale tree information instead of actually updating it. This refresh command is not working.

**Comment by cipriangal** [comment]
i'll take care of this over the weekend.

**Comment by cipriangal** [comment]
Fix: https://github.com/JeffersonLab/japan/commit/17fe99e29a460bd32c9317692c196b14a3043c5a

It seems the problem is related to the TTree::Refresh(). The "OLDTIMERUPDATE" basically just closes the file and reopens it and redoes the plots.

Without it we just kept the file open, ran a t->Refresh() for all the TTrees and redo the plots. The result seems to be that the mean of a 1D distribution is preserved but the width is reduced to nothing (1e-5) and that is what gets drawn. This bug can be reproduced from the root prompt: the range and binning seem to be preserved.

Since the OLDTIMERUPDATE version of the code seems to work I won't look at this any further. If we get more problems we should reopen this issue.
